@startuml
class TileDestroyable {
    + TileDestroyable(texture:Texture2D, spritePos:Point, collision:CollisionType, pass:PassType, heatBoxWidth:int, heatBoxHeigth:int, heatBoxPosX:int, heatBoxPosY:int, posX:int, posY:int)
    + <<override>> Update(gameTime:GameTime) : void
    + <<override>> Draw(spriteBatch:SpriteBatch, gameTime:GameTime, opacity:float) : void
    + Destroy() : void
}
Tile <|-- TileDestroyable
@enduml
