@startuml
class TileFunctional {
    - type : FunctionType
    + TileFunctional(texture:Texture2D, spritePos:Point, collision:CollisionType, pass:PassType, type:FunctionType, heatBoxWidth:int, heatBoxHeigth:int, heatBoxPosX:int, heatBoxPosY:int, posX:int, posY:int)
    + <<override>> Update(gameTime:GameTime) : void
    + <<override>> Draw(spriteBatch:SpriteBatch, gameTime:GameTime, opacity:float) : void
    + Type : FunctionType <<get>>
}
enum FunctionType {
    EXIT,
    ENTRANCE,
    DEADLY,
    TRIGGER,
}
Tile <|-- TileFunctional
TileFunctional +-- FunctionType
@enduml
