@startuml
class ScreenError {
    - catchedException : Exception
    + ScreenError(exception:Exception)
    + <<override>> Initialize() : void
    + <<override>> LoadContent(contentManager:ContentManager) : void
    + <<override>> Update(gameTime:GameTime) : void
    + <<override>> Draw(spriteBatch:SpriteBatch, gameTime:GameTime) : void
}
Screen <|-- ScreenError
@enduml
