@startuml
class ScreenManager {
    - {static} instance : ScreenManager
    - screenStack : Stack<Screen>
    - screenContent : ContentManager
    - ScreenManager()
    + {static} GetInstance() : ScreenManager
    + ChangeScreen(screen:Screen, clearPrevious:bool) : void
    + ReturnPreviousScreen() : void
    + Initialize() : void
    + LoadContent(contentManager:ContentManager) : void
    + UnloadContent() : void
    + Update(gameTime:GameTime) : void
    + Draw(spriteBatch:SpriteBatch, gameTime:GameTime) : void
}
@enduml
