@startuml
class MappedLevelParts {
    backgroundId : int
    roomSize : int
    layerBase : Tile[,]
    layerBack : Tile[,]
    layerDeco : Tile[,]
    layerFunctional : Tile[,]
    movingPlatforms : List<TileMovingPlatform>
    + MappedLevelParts(backgroundId:int, roomSize:int, layerBase:Tile[,], layerBack:Tile[,], layerDeco:Tile[,], layerFunctional:Tile[,], movingPlatforms:List<TileMovingPlatform>)
    + BackgoundId : int <<get>>
    + RoomSize : int <<get>>
    + LayerBase : Tile[,] <<get>>
    + LayerBack : Tile[,] <<get>>
    + LayerDeco : Tile[,] <<get>>
    + LayerFunctional : Tile[,] <<get>>
    + MovingPlatforms : List<TileMovingPlatform> <<get>>
}
@enduml
