@startuml
class TileCreator {
    - calcTileSideSize : int
    - tileIdMap : Dictionary<int, string>
    - tileSet : Texture2D
    - tileSetSize : Point
    - tilePosOnTexture : Point
    + TileCreator(tileIdMap:Dictionary<int, string>, tileSet:Texture2D, tileSetSize:Point)
    + CreateTile(tileId:int, tilePosX:int, tilePosY:int) : Tile
    - GetTilePosOnTextureById(tileId:int) : Point
}
@enduml
