@startuml
class UnmappedLevelParts {
    backgroundId : int
    roomSize : int
    layerBase : int[]
    layerBack : int[]
    layerDeco : int[]
    layerFunctional : int[]
    movingPlatforms : List<int[]>
    entities : List<int[]>
    + UnmappedLevelParts(backgroundId:int, roomSize:int, layerBase:int[], layerBack:int[], layerDeco:int[], layerFunctional:int[], movingPlatforms:List<int[]>)
    + BackgroundId : int <<get>>
    + RoomSize : int <<get>>
    + LayerBase : int[] <<get>>
    + LayerBack : int[] <<get>>
    + LayerDeco : int[] <<get>>
    + LayerFunctional : int[] <<get>>
    + MovingPlatforms : List<int[]> <<get>>
}
@enduml
