@startuml
class TileIdMapFormatException {
    + TileIdMapFormatException(message:string)
    + TileIdMapFormatException(message:string, innerException:Exception)
}
FormatException <|-- TileIdMapFormatException
@enduml
